-- AlterTable
ALTER TABLE "Bet" ADD COLUMN     "basePoints" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "points" SET DEFAULT 0,
ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "MatchExtraConfig" ADD COLUMN     "cardPoints" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "goalPoints" DOUBLE PRECISION NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "StageExtraConfig" ADD COLUMN     "cardPoints" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "goalPoints" DOUBLE PRECISION NOT NULL DEFAULT 1;
